apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    name: mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-pod
  template:
    metadata:
      name: mysql-pod
      labels:
        name: mysql-pod
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        imagePullPolicy: Always #https://kubernetes.io/docs/concepts/configuration/overview/
        envFrom:
          - configMapRef:
              name: mysql-config
          - secretRef:
              name: mysecret
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim